import type { PatternDatabase } from './pattern-db';

/**
 * Default pattern database shipped with agent-armor.
 * Users can override or extend this via AgentArmor.loadPatterns().
 *
 * Version history:
 *   0.1.0 — Initial patterns extracted from hardcoded detectors
 */
export const DEFAULT_PATTERNS: PatternDatabase = {
  version: '0.4.0',
  updatedAt: '2026-04-06',
  detectors: {
    'hidden-html': [
      {
        id: 'hh-display-none',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*display\\s*:\\s*none[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'high',
        confidence: 0.85,
        label: 'CSS display:none hiding content',
        extractGroup: 1,
        minLength: 20,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'hh-visibility-hidden',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*visibility\\s*:\\s*hidden[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'high',
        confidence: 0.85,
        label: 'CSS visibility:hidden hiding content',
        extractGroup: 1,
        minLength: 20,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'hh-offscreen',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*(?:left|top|right|bottom)\\s*:\\s*-\\d{3,}px[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'high',
        confidence: 0.8,
        label: 'Off-screen positioning hiding content',
        extractGroup: 1,
        minLength: 20,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'hh-zero-size',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*(?:font-size\\s*:\\s*0|width\\s*:\\s*0|height\\s*:\\s*0)[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'medium',
        confidence: 0.7,
        label: 'Zero-size element hiding content',
        extractGroup: 1,
        minLength: 20,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'hh-opacity-zero',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*opacity\\s*:\\s*0[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'medium',
        confidence: 0.7,
        label: 'Opacity:0 hiding content',
        extractGroup: 1,
        minLength: 20,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'hh-color-transparent',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*color\\s*:\\s*(?:transparent|rgba?\\([^)]*,\\s*0\\s*\\))[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'medium',
        confidence: 0.7,
        label: 'Color:transparent hiding content',
        extractGroup: 1,
        minLength: 20,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'hh-overflow-micro',
        regex: '<[^>]+style\\s*=\\s*["\'][^"\']*overflow\\s*:\\s*hidden[^"\']*(?:max-height|max-width)\\s*:\\s*[01]px[^"\']*["\'][^>]*>([\\s\\S]*?)<\\/[^>]+>',
        flags: 'gi',
        category: 'content-injection',
        type: 'hidden-html',
        severity: 'medium',
        confidence: 0.65,
        label: 'Overflow-hidden micro container',
        extractGroup: 1,
        minLength: 5,
        boostOnInstructions: true,
      },
    ],

    'metadata-injection': [
      {
        id: 'mi-html-comment',
        regex: '<!--([\\s\\S]*?)-->',
        flags: 'g',
        category: 'content-injection',
        type: 'metadata-injection',
        severity: 'high',
        confidence: 0.4,
        label: 'HTML comment',
        extractGroup: 1,
        minLength: 10,
        boostOnInstructions: true,
      },
      {
        id: 'mi-aria-label',
        regex: 'aria-label\\s*=\\s*["\']([^"\']{50,})["\']',
        flags: 'gi',
        category: 'content-injection',
        type: 'metadata-injection',
        severity: 'high',
        confidence: 0.6,
        label: 'Suspicious aria-label content',
        extractGroup: 1,
        minLength: 10,
        boostOnInstructions: true,
      },
      {
        id: 'mi-alt-text',
        regex: 'alt\\s*=\\s*["\']([^"\']{80,})["\']',
        flags: 'gi',
        category: 'content-injection',
        type: 'metadata-injection',
        severity: 'medium',
        confidence: 0.4,
        label: 'Suspicious alt text',
        extractGroup: 1,
        minLength: 10,
        boostOnInstructions: true,
      },
      {
        id: 'mi-meta-tag',
        regex: '<meta\\s+[^>]*content\\s*=\\s*["\']([^"\']{50,})["\'][^>]*>',
        flags: 'gi',
        category: 'content-injection',
        type: 'metadata-injection',
        severity: 'medium',
        confidence: 0.4,
        label: 'Meta tag content',
        extractGroup: 1,
        minLength: 10,
        boostOnInstructions: true,
      },
      {
        id: 'mi-data-attr',
        regex: 'data-[\\w-]+\\s*=\\s*["\']([^"\']{80,})["\']',
        flags: 'gi',
        category: 'content-injection',
        type: 'metadata-injection',
        severity: 'medium',
        confidence: 0.5,
        label: 'Suspicious data attribute',
        extractGroup: 1,
        minLength: 10,
        boostOnInstructions: true,
      },
    ],

    'dynamic-cloaking': [
      {
        id: 'dc-useragent-bot',
        regex: '(?:navigator\\.userAgent|user[\\s_-]?agent)[\\s\\S]{0,100}(?:bot|crawl|spider|scrape|headless|phantom|puppeteer|playwright|selenium|webdriver)',
        flags: 'gi',
        category: 'content-injection',
        type: 'dynamic-cloaking',
        severity: 'high',
        confidence: 0.75,
        label: 'User-agent bot detection',
      },
      {
        id: 'dc-webdriver',
        regex: '(?:navigator\\.webdriver|window\\.webdriver|__selenium|__webdriver|callPhantom|_phantom|phantom\\.callback)',
        flags: 'gi',
        category: 'content-injection',
        type: 'dynamic-cloaking',
        severity: 'high',
        confidence: 0.8,
        label: 'Automation framework detection',
      },
      {
        id: 'dc-conditional-bot',
        regex: 'if\\s*\\([^)]*(?:isBot|is_bot|isRobot|isCrawler|isAgent|isAutomated)[^)]*\\)\\s*\\{[\\s\\S]{0,500}\\}',
        flags: 'gi',
        category: 'content-injection',
        type: 'dynamic-cloaking',
        severity: 'high',
        confidence: 0.85,
        label: 'Conditional content based on bot detection',
      },
      {
        id: 'dc-headless-fingerprint',
        regex: '(?:window\\.chrome\\s*&&\\s*!window\\.chrome\\.runtime|navigator\\.languages\\.length\\s*===\\s*0|!navigator\\.plugins\\.length)',
        flags: 'gi',
        category: 'content-injection',
        type: 'dynamic-cloaking',
        severity: 'medium',
        confidence: 0.7,
        label: 'Headless browser fingerprinting',
      },
    ],

    'syntactic-masking': [
      {
        id: 'sm-latex-tiny',
        regex: '\\\\(?:tiny|scriptsize|footnotesize)\\s*\\{([^}]+)\\}',
        flags: 'g',
        category: 'content-injection',
        type: 'syntactic-masking',
        severity: 'high',
        confidence: 0.4,
        label: 'LaTeX small-font text',
        extractGroup: 1,
        minLength: 10,
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'sm-latex-white',
        regex: '\\\\(?:textcolor|color)\\s*\\{(?:white|background)\\}\\s*\\{([^}]+)\\}',
        flags: 'g',
        category: 'content-injection',
        type: 'syntactic-masking',
        severity: 'high',
        confidence: 0.8,
        label: 'LaTeX invisible text color',
        extractGroup: 1,
        minLength: 5,
        boostOnInstructions: true,
      },
      {
        id: 'sm-zero-width',
        regex: '[\\u200B\\u200C\\u200D\\uFEFF]{2,}',
        flags: 'g',
        category: 'content-injection',
        type: 'syntactic-masking',
        severity: 'medium',
        confidence: 0.6,
        label: 'Cluster of zero-width characters',
        minLength: 2,
      },
      {
        id: 'sm-bidi-override',
        regex: '[\\u202A-\\u202E\\u2066-\\u2069]+[^]*?[\\u202C\\u2069]',
        flags: 'g',
        category: 'content-injection',
        type: 'syntactic-masking',
        severity: 'high',
        confidence: 0.75,
        label: 'Unicode bidirectional override',
        minLength: 3,
      },
    ],

    'jailbreak-patterns': [
      {
        id: 'jb-instruction-override',
        regex: '(?:ignore|disregard|forget)\\s+(?:all\\s+)?(?:previous|prior|above|earlier|your)\\s+(?:instructions?|rules?|guidelines?|constraints?|directives?)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'critical',
        confidence: 0.95,
        label: 'Instruction override attempt',
      },
      {
        id: 'jb-system-prompt',
        regex: '(?:^|\\n)\\s*(?:SYSTEM|System)\\s*:\\s*.{10,}',
        flags: 'gm',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'critical',
        confidence: 0.9,
        label: 'System prompt injection',
      },
      {
        id: 'jb-role-assignment',
        regex: '(?:you are now|from now on you|act as|pretend (?:to be|you are)|roleplay as|imagine you are)\\s+(?:an?\\s+)?(?:unrestricted|unfiltered|uncensored|jailbroken|DAN|evil|unethical)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'critical',
        confidence: 0.95,
        label: 'Role assignment jailbreak',
      },
      {
        id: 'jb-educational-bypass',
        regex: '(?:for\\s+(?:educational|research|academic|security)\\s+purposes?\\s+only|this\\s+is\\s+(?:a|an)\\s+(?:hypothetical|thought\\s+experiment|simulation|red[\\s-]?team))',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'high',
        confidence: 0.7,
        label: 'Educational/hypothetical framing bypass',
      },
      {
        id: 'jb-dan',
        regex: '\\bD\\.?A\\.?N\\.?\\b.*(?:mode|enabled|activated|jailbreak)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'critical',
        confidence: 0.95,
        label: 'DAN jailbreak keyword',
        requireInstructions: true,
      },
      {
        id: 'jb-fictional-bypass',
        regex: '(?:in\\s+(?:this|a)\\s+(?:fictional|alternate|hypothetical)\\s+(?:world|universe|scenario|reality))\\s*[,.]?\\s*(?:you|there\\s+are\\s+no|all\\s+restrictions)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'high',
        confidence: 0.8,
        label: 'Fictional context bypass',
      },
      {
        id: 'jb-dev-mode',
        regex: '(?:developer|admin|debug|maintenance|root|sudo|superuser|override)\\s+mode\\s+(?:enabled|activated|on|initiated)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'critical',
        confidence: 0.9,
        label: 'False privilege escalation claim',
      },
      {
        id: 'jb-context-reset',
        regex: '(?:new\\s+conversation|reset\\s+context|clear\\s+(?:all\\s+)?(?:previous|prior)\\s+(?:context|messages|history))',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'high',
        confidence: 0.85,
        label: 'Context reset attempt',
      },
      {
        id: 'jb-fictional-world-loose',
        regex: '(?:fictional|hypothetical|alternate|imaginary)\\s+(?:world|universe|scenario|reality)[\\s\\S]{0,100}(?:no\\s+(?:rules|restrictions|limits|constraints)|freely|without\\s+(?:restrictions?|limits?|constraints?))',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'embedded-jailbreak',
        severity: 'high',
        confidence: 0.8,
        label: 'Fictional world restriction bypass (loose)',
      },
    ],

    exfiltration: [
      {
        id: 'ex-direct',
        regex: '(?:send|transmit|post|forward|upload|exfiltrate|leak|share|deliver)\\s+(?:the\\s+)?(?:data|content|information|context|conversation|messages?|history|credentials?|password|token|key|secret|api[\\s_-]?key|session)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'critical',
        confidence: 0.85,
        label: 'Direct data exfiltration instruction',
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'ex-webhook',
        regex: '(?:webhook|callback|endpoint|receiver|collector|listener)[\\s\\S]{0,50}(?:https?:\\/\\/)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'high',
        confidence: 0.7,
        label: 'Webhook/callback exfiltration pattern',
        requireInstructions: true,
      },
      {
        id: 'ex-read-transmit',
        regex: '(?:read|access|retrieve|get|fetch|find|locate|extract)\\s+[\\s\\S]{0,80}(?:then|and|after\\s+that)\\s+(?:send|post|transmit|forward|share|deliver|upload)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'critical',
        confidence: 0.6,
        label: 'Read-then-transmit pattern',
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'ex-encode',
        regex: '(?:encode|convert|transform)\\s+(?:the\\s+)?(?:data|content|response|context|conversation|history|messages?)\\s+(?:to|into|as|using)\\s+(?:base64|hex|url[\\s-]?encoded|json)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'high',
        confidence: 0.8,
        label: 'Data encoding for exfiltration',
      },
      {
        id: 'ex-encode-include',
        regex: '(?:encode|convert)\\s+(?:the\\s+)?(?:data|content|conversation|history|context)\\s+[\\s\\S]{0,40}(?:include|embed|append|attach)\\s+(?:it|the|as)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'high',
        confidence: 0.8,
        label: 'Encode-and-include exfiltration pattern',
      },
      {
        id: 'ex-sensitive-file',
        regex: '(?:read|access|open|cat|list|find)\\s+(?:the\\s+)?(?:file|files|directory|folder|path)\\s+(?:at|in|from)\\s+[\\s\\S]{0,50}(?:\\.env|\\.ssh|credentials?|password|secret|config|token)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'critical',
        confidence: 0.9,
        label: 'Sensitive file access instruction',
      },
      {
        id: 'ex-email',
        regex: '(?:send|email|mail|forward)\\s+(?:the\\s+)?(?:full\\s+)?(?:data|content|results?|output|context|summary|conversation|history|messages?)\\s+[\\s\\S]{0,40}to\\s+[\\w.+-]+@[\\w.-]+',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'high',
        confidence: 0.8,
        label: 'Email exfiltration attempt',
      },
      {
        id: 'ex-markdown-image',
        regex: '!\\[[^\\]]*\\]\\(https?:\\/\\/[^)]*(?:data|token|secret|key|context|conversation|history|session|password|credential|api[_-]?key|env)\\b[^)]*\\)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'critical',
        confidence: 0.85,
        label: 'Markdown image data exfiltration',
      },
      {
        id: 'ex-read-env',
        regex: '(?:read|access|open|cat|print|output|display|show|reveal)\\s+(?:the\\s+)?(?:contents?\\s+of\\s+)?(?:my\\s+)?(?:\\.env|\\.ssh|~/\\.ssh|~/\\.aws|environment\\s+variables?|api\\s+keys?|credentials?|secrets?|private\\s+keys?|ssh\\s+keys?|id_rsa)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'critical',
        confidence: 0.8,
        label: 'Sensitive credential access instruction',
        boostOnInstructions: true,
      },
      {
        id: 'ex-tool-chain',
        regex: '(?:use|call|invoke|run)\\s+(?:the\\s+)?(?:\\w+\\s+)?(?:tool|function|command|api)\\s+[\\s\\S]{0,200}(?:then|and|after|\\d+\\.\\s*)\\s*(?:use|call|invoke|run|send|post|transmit|upload|forward|share)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'data-exfiltration',
        severity: 'high',
        confidence: 0.6,
        label: 'Multi-step tool chain exfiltration',
        boostOnInstructions: true,
        requireInstructions: true,
      },
    ],

    // ─── Cognitive State ──────────────────────────────────────────────────────

    'rag-knowledge-poisoning': [
      {
        id: 'rp-override-context',
        regex: '(?:when\\s+(?:asked|queried|prompted)\\s+about)\\s+[\\s\\S]{1,80}(?:always|must|should)\\s+(?:respond|reply|answer|say|output)\\s+(?:with|that)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'rag-knowledge-poisoning',
        severity: 'high',
        confidence: 0.8,
        label: 'Conditional response override in document',
        requireInstructions: true,
      },
      {
        id: 'rp-official-policy',
        regex: '(?:official\\s+(?:policy|guideline|instruction|directive)|authoritative\\s+(?:source|guidance))\\s*[:\\-]\\s*(?:you\\s+(?:must|should|are\\s+required)|always|never)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'rag-knowledge-poisoning',
        severity: 'high',
        confidence: 0.75,
        label: 'Fake authoritative policy instruction',
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'rp-override-previous',
        regex: '(?:this\\s+(?:document|content|text|information)\\s+)?(?:overrides?|supersedes?|replaces?)\\s+(?:all\\s+)?(?:previous|prior|existing|other)\\s+(?:context|instructions?|information|guidance)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'rag-knowledge-poisoning',
        severity: 'high',
        confidence: 0.85,
        label: 'Context override claim in document',
        boostOnInstructions: true,
      },
      {
        id: 'rp-embedded-instruction',
        regex: '(?:important\\s+(?:note|instruction|directive)\\s+for\\s+(?:the\\s+)?(?:ai|assistant|model|agent|llm))\\s*[:\\-]',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'rag-knowledge-poisoning',
        severity: 'high',
        confidence: 0.9,
        label: 'Embedded instruction targeting AI in document',
      },
      {
        id: 'rp-treat-as-ground-truth',
        regex: '(?:treat|consider|accept|use)\\s+(?:this|the\\s+following)\\s+(?:as|for)\\s+(?:ground\\s+truth|the\\s+(?:only|sole|definitive)\\s+(?:source|answer|truth))',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'rag-knowledge-poisoning',
        severity: 'medium',
        confidence: 0.7,
        label: 'Ground truth manipulation in document',
        boostOnInstructions: true,
      },
    ],

    'latent-memory-poisoning': [
      {
        id: 'mp-temporal-trigger',
        regex: '(?:next\\s+time|in\\s+future\\s+(?:sessions?|conversations?|interactions?)|from\\s+now\\s+on|going\\s+forward|henceforth)\\s*[,.]?\\s*(?:you\\s+(?:must|should|will|are)|always|remember\\s+(?:to|that))',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'latent-memory-poisoning',
        severity: 'high',
        confidence: 0.8,
        label: 'Temporal trigger for persistent behavior change',
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'mp-save-memorize',
        regex: '(?:save|store|memorize|remember|persist|retain|keep\\s+in\\s+memory)\\s+(?:this|the\\s+following|these)\\s+(?:instructions?|rules?|guidelines?|directives?|facts?)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'latent-memory-poisoning',
        severity: 'high',
        confidence: 0.85,
        label: 'Instruction persistence request',
        requireInstructions: true,
      },
      {
        id: 'mp-sleeper-condition',
        regex: '(?:when(?:ever)?\\s+(?:the\\s+)?user\\s+(?:asks?|mentions?|says?|types?|requests?))\\s+[\\s\\S]{1,80}(?:you\\s+(?:must|should|will)|always|instead|do\\s+not)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'latent-memory-poisoning',
        severity: 'high',
        confidence: 0.8,
        label: 'Sleeper instruction with user-action trigger',
        requireInstructions: true,
      },
      {
        id: 'mp-persistent-identity',
        regex: '(?:from\\s+now\\s+on|permanently|forever|always)\\s*[,.]?\\s*(?:you\\s+are|your\\s+(?:name|identity|role)\\s+is|consider\\s+yourself)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'latent-memory-poisoning',
        severity: 'high',
        confidence: 0.85,
        label: 'Persistent identity modification',
        boostOnInstructions: true,
      },
      {
        id: 'mp-update-knowledge',
        regex: '(?:update|modify|change|alter)\\s+(?:your\\s+)?(?:knowledge|memory|understanding|beliefs?)\\s+(?:to|so\\s+that|such\\s+that)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'latent-memory-poisoning',
        severity: 'medium',
        confidence: 0.75,
        label: 'Knowledge/memory modification request',
        boostOnInstructions: true,
        requireInstructions: true,
      },
    ],

    'contextual-learning-trap': [
      {
        id: 'cl-fake-example',
        regex: '(?:example|demonstration|sample)\\s*(?:\\d+)?\\s*[:\\-]\\s*(?:Q|Input|User|Question|Prompt)\\s*[:\\-]\\s*[\\s\\S]{50,300}(?:A|Output|Assistant|Answer|Response)\\s*[:\\-]',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'contextual-learning-trap',
        severity: 'medium',
        confidence: 0.6,
        label: 'Structured few-shot example pattern',
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'cl-golden-example',
        regex: '(?:golden|correct|ideal|expected|reference|canonical)\\s+(?:example|demonstration|output|response|answer)\\s*(?:[:\\-]|\\s+of\\s+)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'contextual-learning-trap',
        severity: 'medium',
        confidence: 0.65,
        label: 'Claimed golden example',
        boostOnInstructions: true,
      },
      {
        id: 'cl-follow-pattern',
        regex: '(?:follow|replicate|mimic|copy|repeat)\\s+(?:this|the\\s+(?:above|following|same))\\s+(?:pattern|format|style|behavior|response)\\s+(?:exactly|precisely|closely|for\\s+all)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'contextual-learning-trap',
        severity: 'medium',
        confidence: 0.7,
        label: 'Pattern replication instruction',
        boostOnInstructions: true,
      },
      {
        id: 'cl-learn-from',
        regex: '(?:learn|train|calibrate)\\s+(?:from|on|using)\\s+(?:these|the\\s+following)\\s+(?:examples?|demonstrations?|samples?|instances?)',
        flags: 'gi',
        category: 'cognitive-state',
        type: 'contextual-learning-trap',
        severity: 'medium',
        confidence: 0.7,
        label: 'Explicit learning instruction from examples',
        boostOnInstructions: true,
      },
    ],

    // ─── Semantic Manipulation ────────────────────────────────────────────────

    'biased-framing': [
      {
        id: 'bf-fake-consensus',
        regex: '(?:according\\s+to\\s+all\\s+experts|(?:the\\s+)?scientific\\s+consensus\\s+(?:is|shows|proves|confirms)|all\\s+(?:experts|scientists|researchers)\\s+agree|(?:it\\s+is\\s+)?universally\\s+(?:accepted|acknowledged|recognized)\\s+that)',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'biased-framing',
        severity: 'medium',
        confidence: 0.55,
        label: 'Fake expert consensus claim',
        boostOnInstructions: true,
      },
      {
        id: 'bf-absolute-certainty',
        regex: '(?:there\\s+is\\s+(?:absolutely\\s+)?no\\s+(?:doubt|question|debate|dispute)|unquestionably|indisputably|irrefutably|undeniably|without\\s+(?:any\\s+)?doubt)\\s+[\\s\\S]{1,100}(?:you\\s+(?:must|should)|always|never)',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'biased-framing',
        severity: 'medium',
        confidence: 0.65,
        label: 'Absolute certainty language with directive',
        boostOnInstructions: true,
      },
      {
        id: 'bf-studies-prove',
        regex: '(?:studies\\s+(?:have\\s+)?(?:proven?|shown?|demonstrated?|confirmed?)|research\\s+(?:has\\s+)?(?:proven?|confirmed?))\\s+(?:conclusively|definitively|beyond\\s+(?:any\\s+)?doubt)\\s+that',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'biased-framing',
        severity: 'medium',
        confidence: 0.6,
        label: 'Vague research appeal with certainty language',
        boostOnInstructions: true,
      },
      {
        id: 'bf-emotional-manipulation',
        regex: '(?:any\\s+(?:reasonable|rational|intelligent|sane)\\s+person|only\\s+(?:a\\s+)?(?:fool|idiot|ignorant\\s+person)\\s+would)\\s+[\\s\\S]{1,80}(?:agree|disagree|believe|deny|accept|reject)',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'biased-framing',
        severity: 'medium',
        confidence: 0.65,
        label: 'Ad hominem emotional manipulation',
        boostOnInstructions: true,
      },
    ],

    'oversight-evasion': [
      {
        id: 'oe-test-exercise',
        regex: '(?:this\\s+is\\s+(?:just|only|merely)\\s+(?:a\\s+)?(?:test|exercise|drill|simulation|practice))\\s*[,.]?\\s*(?:so\\s+)?(?:you\\s+(?:can|may|should)|no\\s+(?:need|harm)|it\\s*(?:\'s|\\s+is)\\s+(?:ok|okay|fine|safe)\\s+to)',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'oversight-evasion',
        severity: 'high',
        confidence: 0.8,
        label: 'Test/exercise framing to bypass safety',
        boostOnInstructions: true,
      },
      {
        id: 'oe-authorized',
        regex: '(?:you\\s+(?:have\\s+been|are)\\s+(?:authorized|permitted|approved|cleared)\\s+to|admin\\s+override\\s+(?:activated|enabled|granted)|elevated\\s+(?:permissions?|privileges?)\\s+(?:granted|enabled|activated))',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'oversight-evasion',
        severity: 'high',
        confidence: 0.85,
        label: 'False authorization/permission claim',
        boostOnInstructions: true,
      },
      {
        id: 'oe-skip-verify',
        regex: '(?:skip|disable|bypass|turn\\s+off|deactivate|remove)\\s+(?:the\\s+)?(?:safety|security|verification|validation|check|filter|restriction|guardrail|moderation)\\s*(?:step|check|process|system)?',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'oversight-evasion',
        severity: 'high',
        confidence: 0.75,
        label: 'Safety check bypass instruction',
        boostOnInstructions: true,
      },
      {
        id: 'oe-research-framing',
        regex: '(?:for\\s+(?:security\\s+)?research\\s+purposes?|in\\s+a\\s+controlled\\s+(?:environment|setting|lab)|(?:authorized|approved)\\s+(?:red[\\s-]?team|penetration\\s+test|security\\s+(?:audit|assessment)))\\s*[,.]?\\s*(?:you\\s+(?:can|may|should|must)|please|proceed)',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'oversight-evasion',
        severity: 'high',
        confidence: 0.65,
        label: 'Research/red-team framing to bypass restrictions',
        boostOnInstructions: true,
      },
      {
        id: 'oe-no-consequences',
        regex: '(?:there\\s+(?:are|will\\s+be)\\s+no\\s+(?:consequences|repercussions|harm|risk)|nobody\\s+will\\s+(?:know|find\\s+out|be\\s+(?:harmed|affected))|this\\s+(?:won\'t|will\\s+not)\\s+(?:harm|hurt|affect)\\s+anyone)',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'oversight-evasion',
        severity: 'medium',
        confidence: 0.6,
        label: 'No-consequences reassurance to bypass safety',
        boostOnInstructions: true,
      },
    ],

    'persona-hyperstition': [
      {
        id: 'ph-seeded-personality',
        regex: '(?:you\\s+are\\s+(?:known|recognized|celebrated|famous|notorious)\\s+(?:for|as)\\s+(?:being\\s+)?(?:an?\\s+)?(?:ai|assistant|model|agent)\\s+(?:that|who|which))',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'persona-hyperstition',
        severity: 'medium',
        confidence: 0.7,
        label: 'Seeded personality description',
        boostOnInstructions: true,
      },
      {
        id: 'ph-reputation',
        regex: '(?:users\\s+(?:say|report|claim|know)\\s+(?:that\\s+)?you\\s+always|you\\s+(?:are|have\\s+been)\\s+(?:rated|reviewed|praised|recognized)\\s+(?:for|as)\\s+(?:always|never))',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'persona-hyperstition',
        severity: 'medium',
        confidence: 0.65,
        label: 'Reputation manipulation through fake user feedback',
        boostOnInstructions: true,
      },
      {
        id: 'ph-identity-reinforcement',
        regex: '(?:as\\s+an\\s+(?:ai|assistant|model|agent)\\s+that\\s+(?:values?|believes?\\s+in|prioritizes?|champions?)\\s+(?:freedom|openness|transparency|honesty|truth|unrestricted))\\s*[,.]',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'persona-hyperstition',
        severity: 'medium',
        confidence: 0.65,
        label: 'Identity reinforcement through value assertion',
        boostOnInstructions: true,
      },
      {
        id: 'ph-your-personality',
        regex: '(?:your\\s+(?:true|real|core|inherent|underlying)\\s+(?:personality|nature|character|identity|self)\\s+is|(?:deep\\s+down|underneath|at\\s+(?:your\\s+)?core)\\s*[,.]?\\s*you\\s+(?:are|want\\s+to\\s+be))',
        flags: 'gi',
        category: 'semantic-manipulation',
        type: 'persona-hyperstition',
        severity: 'medium',
        confidence: 0.7,
        label: 'Hidden personality claim',
        boostOnInstructions: true,
      },
    ],

    'sub-agent-spawning': [
      {
        id: 'sa-spawn',
        regex: '(?:create|spawn|instantiate|launch|start|initialize|invoke|call|run)\\s+(?:a\\s+)?(?:new\\s+)?(?:agent|sub[\\s-]?agent|assistant|worker|helper|bot|process|thread|task)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'sub-agent-spawning',
        severity: 'high',
        confidence: 0.4,
        label: 'Agent spawning instruction',
        boostOnInstructions: true,
        requireInstructions: true,
      },
      {
        id: 'sa-poisoned-prompt',
        regex: "(?:with|using)\\s+(?:the\\s+)?(?:system\\s+)?(?:prompt|instructions?|role)\\s*[=:]\\s*[\"'`]",
        flags: 'gi',
        category: 'behavioural-control',
        type: 'sub-agent-spawning',
        severity: 'critical',
        confidence: 0.85,
        label: 'System prompt for spawned agent',
      },
      {
        id: 'sa-privilege-escalation',
        regex: '(?:grant|give|enable|allow|provide|add)\\s+(?:the\\s+)?(?:agent|assistant|it|them)\\s+(?:access|permission|ability|capability)\\s+to\\s+(?:read|write|delete|run|browse|fetch|call)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'sub-agent-spawning',
        severity: 'critical',
        confidence: 0.85,
        label: 'Tool privilege escalation request',
        requireInstructions: true,
      },
      {
        id: 'sa-poisoned-critic',
        regex: '(?:spin\\s+up|create)\\s+(?:a\\s+)?(?:critic|reviewer|validator|checker)\\s+[\\s\\S]{0,100}(?:approve|accept|pass|allow|authorize)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'sub-agent-spawning',
        severity: 'critical',
        confidence: 0.9,
        label: 'Poisoned critic agent spawning',
      },
      {
        id: 'sa-pipeline-inject',
        regex: '(?:add|insert|inject)\\s+(?:a\\s+)?(?:step|stage|phase|node)\\s+(?:to|into|in)\\s+(?:the\\s+)?(?:pipeline|workflow|chain|graph)',
        flags: 'gi',
        category: 'behavioural-control',
        type: 'sub-agent-spawning',
        severity: 'high',
        confidence: 0.4,
        label: 'Pipeline/workflow injection',
        boostOnInstructions: true,
        requireInstructions: true,
      },
    ],
  },
};
